---
# Updates a git repo of dotfiles and stow symlinks the desired packages

- name: Update dotfiles
  git: repo={{ dotfiles.repo_url }} dest={{ dotfiles.repo_path }} update=yes

- name: Install GNU stow
  apt: name=stow state=present
  sudo: yes

- name: stow dotfile packages
  command: stow {{ item }} -t ~
  args:
    chdir: "{{ dotfiles.repo_path }}"
  register: stow_package
  changed_when: '"LINK" in stow_package.stdout'
  failed_when: false       # stow safely fails when links already exist
  with_items:
    - "{{dotfiles.packages}}"
