---
- name: osx-dev Playbook
  hosts: all
  vars:
    dotfiles:
      repo_url: https://github.com/dghubble/dotfiles.git
      repo_path: ~/dotfiles
      packages:
        - { package: bash }
        - { package: git }
  roles:
    - osx-common
    - osx-dev
    - osx-gui