---
- name: osx Playbook
  hosts: all
  vars:
    dotfiles:
      repo_url: https://github.com/dghubble/dotfiles.git
      repo_path: ~/dotfiles
      packages:
        - bash
        - git
  roles:
    - osx/update
    - osx/system
    - osx/files
    - osx/cask
    - osx/dev
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
