---
# Updates a git repo of dotfiles and stow symlinks the desired packages

- name: Update dotfiles
  git: repo={{dotfiles.repo_url}} dest={{dotfiles.repo_path}} update=no
  register: dotfiles_repo

- name: Msg if dotfiles updates are available
  debug: msg="Dotfiles updates are available. Consider pulling the latest changes."
  when: dotfiles_repo.changed == true

- name: Install GNU stow
  homebrew: name=stow state=present

- name: stow dotfile packages
  command: stow {{ item }} -t ~
  args:
    chdir: "{{ dotfiles.repo_path }}"
  register: stow_package
  changed_when: '"LINK" in stow_package.stdout'
  failed_when: false       # stow safely fails when links already exist
  with_items:
    - "{{dotfiles.packages}}"
