---
# setup secrets files

- name: Create an ~/.secrets directory
  file: path=~/.secrets state=directory mode=0700

- name: Check for existence of /Volumes/nagini/secrets
  stat: path=/Volumes/nagini/secrets
  register: volume

# never override existing files (force=no)
- name: Copy secrets files from volume
  copy: src=/Volumes/nagini/secrets/ dest=~/.secrets force=no mode=0600
  when: volume.stat.exists == true

## SSH

- name: Create the ~/.ssh symlink if it does not exist
  file: src=~/.secrets/ssh dest=~/.ssh state=link mode=0700

- name: Set the id_rsa.pub mode to 644
  file: path={{item}} mode=0644
  with_fileglob:
    - ~/.ssh/id_rsa.pub

- name: Set the keypair public key modes to 644
  file: path={{item}} mode=0644
  with_fileglob:
    - ~/.ssh/keypairs/*.pub

- name: Set the keypair *.pem pair modes to 400
  file: path={{item}} mode=0400
  with_fileglob:
    - ~/.ssh/keypairs/*.pem
