---
# System settings

- name: Restart automatically if the computer freezes
  raw: systemsetup -setrestartfreeze on
  sudo: yes

- name: Restart automatically after power failure
  raw: systemsetup -setrestartpowerfailure on
  sudo: yes
