---
# setup general secrets

- name: Create the ~/.secrets directory if it does not exist
  file: path=~/.secrets state=directory mode=0700
  tags: secrets

- name: Check for existence of /Volumes/nagini/secrets
  stat: path=/Volumes/nagini/secrets
  register: nagini
  tags: secrets

# never override existing files (force=no)
# use mode 0600 by default and relax modes when appropriate

- name: Copy secrets into place if they don't exist
  copy: src=/Volumes/nagini/secrets/ dest=~/.secrets force=no mode=0600
  when: nagini.stat.exists == true
  tags: secrets
