---
# tasks file for osx-common

- name: Install Homebrew packages
  homebrew: name={{ item }} state=present
  with_items:
    - ack
    - curl
    - git
    - go
    - vim
    - wget
- include: python.yml
- include: finder.yml

