---
# Copy secrets into place

- name: Check for existence of /Volumes/nagini/secrets
  stat: path=/Volumes/nagini/secrets
  register: horcrux
  tags: secrets

- name: Create the ~/.ssh directory if it does not exist
  file: path=~/.ssh state=directory mode=0700

# Notes:
# Never override existing files (force=no). Use mode 0600 by default and relax
# modes when appropriate
- name: Copy ssh secrets into place if they don't exist
  copy: src=/Volumes/nagini/secrets/ssh/ dest=~/.ssh force=no mode=0600
  when: horcrux.stat.exists == true
  tags: secrets

- name: Set the id_rsa.pub mode to 644
  file: path=~/.ssh/id_rsa.pub mode=0644

- name: Set the keypair public key modes to 644
  file: path={{item}} mode=0644
  with_fileglob:
    - ~/.ssh/keypairs/*.pub

- name: Set the keypair *.pem pair modes to 400
  file: path={{item}} mode=0400
  with_fileglob:
    - ~/.ssh/keypairs/*.pem


