---

# - name: Install Java 8
#   homebrew_cask: name=java state=present

# - name: Install Android Studio
#   homebrew_cask: name=android-studio state=present

# - name: Install Genymotion
#   homebrew_cask: name=genymotion state=present

- name: Check for ~/sources/android-sdk-macosx
  stat: path=~/sources/android-sdk-macosx
  register: sdk

# Android SDK

- name: Add the Android SDK directory
  file: path=~/sources/android-sdk-macosx state=directory

- name: Install the Android SDK
  get_url: url=http://dl.google.com/android/android-sdk_r24.3.3-macosx.zip dest=~/sources/android-sdk-macosx.zip
  when: sdk.stat.exists == false

# https://developer.android.com/sdk/installing/index.html?pkg=tools
- name: Unzip the Android SDK
  unarchive: src=~/sources/android-sdk-macosx.zip dest=~/sources copy=no
  when: sdk.stat.exists == false

- name: Delete the Android SDK .zip
  file: path=~/sources/android-sdk-macosx.zip state=absent