---

- name: Install Docker
  homebrew: name=docker state=present

- name: Install docker-compose
  homebrew: name=docker-compose state=present

- name: Install docker-machine
  homebrew: name=docker-machine state=present
