---
# OSX Python

# Latest Python 2.7.x release, because the OS X default Python is not suitable for development.
# brew install python
# python --version ~ 2.7.9
- name: Install latest Python 2.7.x release
  homebrew: name=python state=latest
# Notes:
# Includes pip (pip --version ~ 6.0.6, installed to /usr/local/lib/python2.7/site-packages)
# Use pip (no sudo) to install packages globally
# Reference:
# * Python releases http://www.python.org/download/releases/
# * Homebrew Python Notes https://github.com/Homebrew/homebrew/tree/master/share/doc/homebrew#readme


# Virtualenv - per-project Python package installation environments.
# pip install virtualenv --upgrade
# virtualenv --version ~ 12.0.5
- name: Install virtualenv (latest)
  pip: name=virtualenv state=latest
# Usage:
# virtualenv --distribute [--python=python3] venv 
# source venv/bin/activate
# deactivate


# Virtualenv-wrapper - per-project Python package installation environments isolated and stored in ~/.virtualenvs. Also provides env var scripts.
# pip install virtualenvwrapper --upgrade
# pip freeze shows ~ 4.3.2
- name: Install virtualenvwrapper (latest)
  pip: name=virtualenvwrapper state=latest
# Notes:
# Installs to /usr/local/lib/python2.7/site-packages
# Usage:
# mkvirtualenv --distribute [--python=python3] project-name (autoactivates it)
# workon project-name
# deactivate
# rmvirtualenv project-name
# lsvirtualenv, cdvirtualenv, cdsitepackages, lssitepackages
# Modify postactivate, postdeactivate in ~/.virtualenvs/project-name/bin to set environment variable or customize the environment.


# Latest Python 3.x.x release
# brew install python3
# python3 --version ~ 3.4.2
- name: Install latest Python 3.4.x release
  homebrew: name=python3 state=latest
# Notes:
# Includes pip3 (pip3 --version ~ 6.0.3, installed to /usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages)
# Use pip3 (no sudo) to install packages globally
# Reference:
# * Python releases http://www.python.org/downloads/
# * Homebrew Python Notes https://github.com/Homebrew/homebrew/tree/master/share/doc/homebrew#readme

- name: Install Sphinx
  pip: name=sphinx state=latest

- name: Install mkdocs
  pip: name=mkdocs state=latest

