---

- name: Install automake
  homebrew: name=automake state=present

- name: Install libtool
  homebrew: name=libtool state=present

- name: Install z tool
  homebrew: name=z state=latest

- name: Install GNU Privacy Guard (GPG)
  homebrew: name=gnupg state=latest